### ISSUE TITLE
is keycode broken?

### ISSUE THREAD

**Issue by Kerumen** [42Zavattas/KeyCode#1]
Hi,

I was about to play a typing game, so I went to https://keycode.fugitive.link/ but nothing happened. I checked my internet by pinging google.com and everything worked. I didn't understood what was happening right now, so I asked a friend to try at his home, and same problem again (ping google worked, and https://keycode.fugitive.link/ didn't worked).

Is it a problem with internet itself, or maybe a problem with keycode. Dunno, but I create the issue now for the moment, and I maybe will create an issue on the internet repo if the problem is not there.

Thanks for your help and your awesome work!

Keycodely,
Yann

**Comment by meriadec** [comment]
I don't know how you find that link, but as in the repo description, the site url is http://keycode.fugitive.link/. Maybe try with the correct link?
